spring:
  datasource:
    url: jdbc:h2:file:./build/h2db/db/products;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    show-sql: true
    properties:
      hibernate:
        default_schema: online_service

  h2:
    console:
      enabled: true
  sql.init.continue-on-error: true
  sql.init.mode: always
  sql.init.platform: h2

